config/routes.rb
Rails.application.routes.draw do
  root to: "users#login", :as => "login"

  get "/signup" => "users#signup", :as => "signup"

  get "/welcome" => "users#welcome", :as => "welcome"

  get "/admin_welcome" => "admins#admin_welcome", :as => "admin_welcome"

  get "/adduser" => "users#adduser", :as => "adduser"

  get "/password" => "admins#password", :as => "password"

  get "/forgot_password_1" => "users#forgot_password_1"

  get "/forgot_password_2" => "users#forgot_password_2"

  get "/forgot_password_3" => "users#forgot_password_3"

  get "/signuplist" => "users#signuplist"

  get "/bidlist" => "users#bidlist"

  get "/pricelist" => "users#pricelist"

  get "/pricecount" => "users#pricecount"

  get "user_two" => "admins#user_two"

  get "show" => "users#show"

  post "user_two" => "admins#user_two"

  post "forgot_password_one" => "users#forgot_password_one"

  post "forgot_password_two" => "users#forgot_password_two"

  post "forgot_password_three" => "users#forgot_password_three"

  post "create_login_session" => "users#create_login_session"

  post "change_password_session" => "admins#change_password_session"

  post "login_activity"  => "users#login_activity"

  post "synchronization" =>  "users#synchronization"

  post "synchronous_bid" => "users#synchronous_bid"

  post "start" => "users#start"

  post "end" => "users#end"

  post "synchronous_show" => "users#synchronous_show"

  post "synchronization_two" => "users#synchronization_two"

  delete "delete_user" => "users#delete_user", :as => "delete_user"

  delete "logout" => "users#logout", :as => "logout"

  delete "logout_two" => "users#logout_two"

  resources :users, only: [:create]

end

app/views/admins/admin_welcome.haml
= render 'shared/header'
- if current_user
  - if current_user.identity == "admin"
    .panel.panel-default{:style => "width: 95%;margin-left: 35px"}
      .panel-heading{:style => "font-size: 25px"}
        用户管理
        = link_to "+添加用户", adduser_path,:class => "btn btn-default"
      %table.table.text-center
        %tr
          %td{:style => "width: 350px"} 编号
          %td{:style => "width: 350px"} 用户名
          %td 操作
        - if params[:page].to_i == 0
          - id = 0
        - else
          - id = (params[:page].to_i-1)*10
        - @user.each do |p|
          %tr
            %td{:style => "width: 350px"}= id =id+1
            %td{:style => "width: 350px"}= link_to p.name,user_two_path(:username_two => p[:name])
            %td
              = link_to "删除", delete_user_path(:delete_name => p[:name]), data: {confirm: "确定要删除"+p[:name]+"这个用户？"}, method: "delete"
              \&nbsp&nbsp&nbsp&nbsp#{link_to "修改密码", password_path(:change_name => p[:name])}
    .pagination{:style => "position: absolute;right: 30px; "}
      = will_paginate @user, {:previous_label => '<<', :next_label => '>>'}
  -#- else
  -#  .panel.panel-default{:style => "width: 95%;margin-left: 35px"}
  -#    .panel-heading{:style => "font-size: 25px"}
  -#      活动信息
  -#    %table.table.text-center
  -#      %tr
  -#        %td{:style => "width: 25%"} 编号
  -#        %td{:style => "width: 25%"} 活动名称
  -#        %td{:style => "width: 25%"} 报名人数
  -#        %td{:style => "width: 25%"} 竞价次数
  -#      - if params[:page].to_i == 0
  -#        - id = 0
  -#      - else
  -#        - id = (params[:page].to_i-1)*10
  -#      - @activity.each do |p|
  -#        %tr
  -#          %td{:style => "width: 25%"}= id =id+1
  -#          %td{:style => "width: 25%"}= link_to p.activityname,bidlist_path(:username => p[:username],:activityname => p[:activityname])
  -#          %td{:style => "width: 25%"}= link_to Activity.where(:username => p.username,:activityname => p.activityname).count,signuplist_path(:username => p[:username],:activityname => p[:activityname])
  -#          %td{:style => "width: 25%"}= BidList.where(:username => p.username,:activityname => p.activityname).count
  -#  .pagination{:style => "position: absolute;right: 30px; "}
  -#    = will_paginate @activity, {:previous_label => '<<', :next_label => '>>'}

app/views/admins/password.haml
#alert.modal
  .modal-dialog
    .modal-content
      .modal-header
        %h4.modal-title
      .modal-body.text-center
        %h4 修改成功
      .modal-footer
        = link_to "确定", admin_welcome_path, :class => "btn btn-default"
= render 'shared/header'
%ol.breadcrumb
  %li= link_to_unless_current "首页", admin_welcome_path
  %li= "修改密码"
.panel.panel-default.panel-body.text-center.center-block.width{:style => "background-color: #eeeeee"}
  = form_tag "change_password_session" do
    .center-block
      %div
        %dl.input-group
          %dt.input-group-addon.input_width-1 &nbsp&nbsp帐&nbsp&nbsp&nbsp号&nbsp&nbsp
          %dd= text_field_tag :name, session[:name], :disabled => 'disabled', :class => "form-control"
        %dl.input-group
          %dt.input-group-addon.input_width-1 设置密码
          %dd
            = password_field_tag :password, params[:password], :class => "form-control"
        %dl.input-group
          %dt.input-group-addon.input_width-1 确认密码
          %dd
            = password_field_tag :password_confirmation, params[:password_confirmation], :class => "form-control"
        - if flash[:error]
          .alert.alert-danger
            = flash[:error]
        - if flash[:notice] == "ok"
          - flash[:notice] = ""
          %script{:language => "javascript"}
            $('#alert').modal('show')
        %p= submit_tag "确认修改", :class => "btn-default btn btm-primary"