config/routes.rb
Rails.application.routes.draw do
  root to: "users#login", :as => "login"

  get "/signup" => "users#signup", :as => "signup"

  get "/welcome" => "users#welcome", :as => "welcome"

  get "/admin_welcome" => "admins#admin_welcome", :as => "admin_welcome"

  get "/adduser" => "users#adduser", :as => "adduser"

  get "/password" => "admins#password", :as => "password"

  get "/forgot_password_1" => "users#forgot_password_1"

  get "/forgot_password_2" => "users#forgot_password_2"

  get "/forgot_password_3" => "users#forgot_password_3"

  get "/signuplist" => "users#signuplist"

  get "/bidlist" => "users#bidlist"

  get "/pricelist" => "users#pricelist"

  get "/pricecount" => "users#pricecount"

  get "user_two" => "admins#user_two"

  get "show" => "users#show"

  post "user_two" => "admins#user_two"

  post "forgot_password_one" => "users#forgot_password_one"

  post "forgot_password_two" => "users#forgot_password_two"

  post "forgot_password_three" => "users#forgot_password_three"

  post "create_login_session" => "users#create_login_session"

  post "change_password_session" => "admins#change_password_session"

  post "login_activity"  => "users#login_activity"

  post "synchronization" =>  "users#synchronization"

  post "synchronous_bid" => "users#synchronous_bid"

  post "start" => "users#start"

  post "end" => "users#end"

  post "synchronous_show" => "users#synchronous_show"

  post "synchronization_two" => "users#synchronization_two"

  delete "delete_user" => "users#delete_user", :as => "delete_user"

  delete "logout" => "users#logout", :as => "logout"

  delete "logout_two" => "users#logout_two"

  resources :users, only: [:create]

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :password, :password_confirmation,:forget_issues,:forget_answer,:identity,:token
  before_create { generate_token(:token) }

  validates :name, :presence => true
  validates :password, :presence => true
  validates :password_confirmation, :presence => true
  validates :forget_issues, :presence => true
  validates :forget_answer, :presence => true
  validates :name,:uniqueness => {:case_sensitive => false}
  has_secure_password

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  def signup
    @user = User.new
  end

  def welcome
    admin_operation
    user_operation
  end

  def admin_operation
    if current_user.identity == "admin" && current_user_two
      activity = Event.where(:username => current_user_two.name)
      @activity = activity.paginate(page: params[:page],per_page:10)
    end
  end

  def user_operation
    if current_user.identity == "user"
      activity = Event.where(:username => current_user.name)
      @activity = activity.paginate(page: params[:page],per_page:10)
    end
  end

  def adduser
    @user = User.new
  end

  def create
    params[:user][:identity] = "user"
    @user = User.new(params[:user])
    if current_user
      admin_add_user
    else
      user_sign_up
    end
  end

  def admin_add_user
    if current_user.identity == "admin"
      if @user.save
        redirect_to :admin_welcome
      else
        render :adduser
      end
    end
  end

  def user_sign_up
    if @user.save
      cookies.permanent[:token] = @user.token
      redirect_to :welcome
    else
      render :signup
    end
  end

  def logout
    cookies.delete(:token)
    redirect_to :login
  end

  def logout_two
    cookies.delete(:token_two)
    redirect_to :admin_welcome
  end

  def create_login_session
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      cookies.permanent[:token] = user.token
      if user.identity == "admin"
        redirect_to :admin_welcome
      else
        redirect_to :welcome
      end
    else
      flash[:error] = "用户名不存在或密码错误"
      redirect_to :login
    end
  end


  def delete_user
    User.find_by_name(params[:delete_name]).delete
    redirect_to :welcome
  end

  def forgot_password_2
    if cookies.permanent[:forget_issues]
      render :forgot_password_2
    else
      redirect_to :forgot_password_1
    end
  end

  def forgot_password_3
    if cookies.permanent[:name]
      render :forgot_password_3
    else
      redirect_to :login
    end
  end

  def forgot_password_one
    if params[:name] == ""
      flash[:error] = "帐号不能为空"
      redirect_to :forgot_password_1
    else
      if User.find_by_name(params[:name])
        cookies.permanent[:name] = User.find_by_name(params[:name]).name
        cookies.permanent[:forget_issues] = User.find_by_name(params[:name]).forget_issues
        redirect_to :forgot_password_2
      else
        flash[:error] = "帐号不存在"
        redirect_to :forgot_password_1
      end
    end
  end

  def forgot_password_two
    if cookies.permanent[:forget_issues]
      if params[:forget_answer] == ""
        flash[:error] = "忘记密码答案不能为空"
        redirect_to :forgot_password_2
      else
        forgot_answer_contains
      end
    else
      redirect_to :forgot_password_1
    end
  end

  def forgot_answer_contains
    if User.find_by_name(cookies.permanent[:name]).forget_answer == params[:forget_answer]
      cookies.delete(:forget_issues)
      redirect_to :forgot_password_3
    else
      flash[:error] = "忘记密码答案错误"
      redirect_to :forgot_password_2
    end
  end

  def forgot_password_three
    if cookies.permanent[:name]
      if params[:password] == "" || params[:password_confirmation] == ""
        flash[:error] = "密码不能为空"
        redirect_to :forgot_password_3
      else
        forgot_password_contains
      end
    else
      redirect_to :login
    end
  end

  def forgot_password_contains
    if params[:password] == params[:password_confirmation]
      user = User.find_by_name(cookies.permanent[:name])
      user.password = params[:password]
      user.password_confirmation = params[:password_confirmation]
      user.save
      cookies.delete(:name)
      cookies.permanent[:token] = user.token
      redirect_to :welcome
    else
      flash[:error] = "两次密码输入不一致，请重新输入"
      redirect_to :forgot_password_3
    end
  end

  def login_activity
    user = User.find_by_name(params[:userName])
    respond_to do |format|
      if user && user.authenticate(params[:userPassword])
        format.json { render json: {data: 'true'} }
      else
        format.json { render json: {data: 'false'} }
      end
    end
  end

  def synchronization
    Event.update_events(params[:username],params[:activity])
    Activity.update_people_list(params[:username],params[:peopleList])
    BidList.update_bid_list(params[:username],params[:bidList])
    BidMessage.update_bid_message(params[:username],params[:bidMessage])
    PriceCount.update_price_count(params[:username],params[:priceCount])
    respond_to do |format|
      format.json {render json: {data:'true'}}
    end
  end

  def synchronization_two
    Activity.update_people_list(params[:username],params[:peopleList])
    respond_to do |format|
      format.json {render json: {data:'true'}}
    end
  end

  def synchronous_bid
    Bid.create(params[:bid])
    respond_to do |format|
      format.json {render json: {data:'true'}}
    end
  end

  def show
    @bid_count = Bid.all
    bid = Bid.where(:count => 1).limit(10)
    @bid = bid
    render :show
  end

  def start
    Bid.delete_all
    Message.delete_all
    Message.create({:name => params[:name],:status => "1"})
    respond_to do |format|
      format.json {render json: {data:'true'}}
    end
  end

  def end
    message = Message.first
    message.status = "0"
    message.save
    respond_to do |format|
      format.json {render json: {data:'true'}}
    end
  end

  def synchronous_show
    message = Message.first
    if message.status == "1"
      redirect_to :show
    else
      redirect_to :welcome
    end
  end
end

app/views/users/adduser.haml
= render 'shared/header'
%ol.breadcrumb
  %li= link_to_unless_current "首页",admin_welcome_path
  %li= "添加用户"
.panel.panel-default.panel-body.text-center.center-block.width{:style => "background-color: #eeeeee"}
  = form_for @user do |f|
    .center-block
      %div
        %dl.input-group
          %dt.input-group-addon= f.label :name, :class => "input_width-1"
          %dd= f.text_field :name, :class => "form-control"
        %dl.input-group
          %dt.input-group-addon
            = f.label :password, :class => "input_width-1"
          %dd
            = f.password_field :password, :class => "form-control"
        %dl.input-group
          %dt.input-group-addon
            = f.label :password_confirmation, :class => "input_width-1"
          %dd
            = f.password_field :password_confirmation, :class => "form-control"
        %dl.input-group
          %dt.input-group-addon
            = f.label :forget_issues
          %dd
            = f.text_field :forget_issues, :class => "form-control"
        %dl.input-group
          %dt.input-group-addon
            = f.label :forget_answer
          %dd
            = f.text_field :forget_answer, :class => "form-control"
        - if @user.errors.any?
          .alert.alert-danger
            = @user.errors.full_messages.first
        %p= f.submit "确认添加", :class => "btn-default btn btm-primary"

app/views/users/bidlist.haml
= render 'shared/header'
.panel.panel-default{:style => "width: 95%;margin-left: 35px"}
  .panel-heading
    %p{:style => "font-size: 25px"}
      竞价列表
    %p{:style => "font-size: 15px;position: absolute;right: 50px;top: 110px"}
      = link_to "报名列表",signuplist_path(:username =>  params[:username],:activityname => params[:activityname])
    - bidlist = BidList.where(:username => params[:username],:activityname => params[:activityname])
    - @bidlist = bidlist.paginate(page: params[:page],per_page:10)
  %table.table.text-center
    %tr
      %td{:style => "width: 30%"} 编号
      %td{:style => "width: 30%"} 名称
      %td{:style => "width: 40%"} 参与人数
    - if params[:page].to_i == 0
      - id = 0
    - else
      - id = (params[:page].to_i-1)*10
    - @bidlist.each do |p|
      %tr
        %td{:style => "width: 30%"}= id =id+1
        %td{:style => "width: 30%"}= link_to "竞价"+p.bidname,pricelist_path(:username =>  params[:username],:activityname => params[:activityname],:bidname => p[:bidname])
        %td{:style => "width: 40%"}
          = BidMessage.where(:username =>  params[:username],:activityname => params[:activityname],:bidname => p.bidname).count
          = "/"
          = Activity.where(:username =>  params[:username],:activityname => params[:activityname]).count
.pagination{:style => "position: absolute;right: 30px; "}
  = will_paginate @bidlist, {:previous_label => '<<', :next_label => '>>'}

app/views/users/changepassword.erb
<div class="panel panel-default panel-body text-center center-block width" style = "background-color: #eeeeee">
  <div class="center-block">
    <h3>修改密码</h3>
    <div class="">
      <%= form_tag "/change_password" do %>
          <dl class="input-group">
            <dt class="input-group-addon">
              <%= label_tag "修改帐号" %>
            </dt>
            <dd class = "">
              <%= text_field_tag :name, params[:name], :class => "form-control" %>
            </dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon">
              <%= label_tag "设置密码" %>
            </dt>
            <dd class = "">
              <%= password_field_tag :password, params[:password], :class => "form-control" %>
            </dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon">
              <%= label_tag "确认密码" %>
            </dt>
            <dd class = "">
              <%= password_field_tag :password_confirmation, params[:password_confirmation], :class => "form-control" %>
            </dd>
          </dl>
          <% if flash[:error] %>
              <div class = "alert alert-danger">
                <%= flash[:error] %>
              </div>
          <% end %>
          <p> <%= submit_tag "确定", :class => "btn-default btn btm-primary" %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/forgot_password_1.haml
= render 'shared/header'
.panel.panel-default.panel-body.text-center.center-block.width{:style => "background-color: #eeeeee"}
  #login.center-block
    %h3 重置密码
    = link_to "用户登录",login_path, :class => "right"
    %div
      = form_tag "/forgot_password_one" do
        %dl.input-group
          %dt.input-group-addon
            = label_tag "帐号"
          %dd
            = text_field_tag :name, params[:name], :class => "form-control",:placeholder => "请输入帐号"
        - if flash[:error]
          .alert.alert-danger
            = flash[:error]
        %p
          = submit_tag "下一步", :class => "btn-default btn btm-primary"

app/views/users/forgot_password_3.haml
= render 'shared/header'
.panel.panel-default.panel-body.text-center.center-block.width{:style => "background-color: #eeeeee"}
  #login.center-block
    %h3 重置密码
    = link_to "用户登录",login_path, :class => "right"
    %div
      = form_tag "/forgot_password_three" do
        %dl.input-group
          %dt.input-group-addon
            = label_tag "请设置密码"
          %dd
            = password_field_tag :password, params[:password], :class => "form-control",:placeholder => "请输入新密码"
        %dl.input-group
          %dt.input-group-addon
            = label_tag "请确认密码"
          %dd
            = password_field_tag :password_confirmation, params[:password_confirmation], :class => "form-control",:placeholder => "请再次输入"
        - if flash[:error]
          .alert.alert-danger
            = flash[:error]
        %p
          = submit_tag "确认修改", :class => "btn-default btn btm-primary"

app/views/users/login.erb
<div class="panel panel-default panel-body text-center center-block width" style = "background-color: #eeeeee">
  <div class="center-block" id="login">
    <h3>登录</h3>
    <%= link_to "用户注册",signup_path, :class => "right" %>
    <div class="">
      <%= form_tag "/create_login_session" do %>
          <dl class="input-group">
            <dt class="input-group-addon">
              <%= label_tag "帐号" %>
            </dt>
            <dd class = "">
              <%= text_field_tag :name, params[:name], :class => "form-control" %>
            </dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon">
              <%= label_tag "密码" %>
            </dt>
            <dd class = "">
              <%= password_field_tag :password, params[:password], :class => "form-control" %>
            </dd>
          </dl>
          <%= link_to "忘记密码",signup_path, :class => "right" %>
          <% if flash[:error] %>
              <div class = "alert alert-danger">
                <%= flash[:error] %>
              </div>
          <% end %>
          <p> <%= submit_tag "登录", :class => "btn-default btn btm-primary" %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/login.haml
= render 'shared/header'
.panel.panel-default.panel-body.text-center.center-block.width{:style => "background-color: #eeeeee"}
  #login.center-block
    %h3 登录
    = link_to "用户注册",signup_path, :class => "right"
    %div
      = form_tag "/create_login_session" do
        %dl.input-group
          %dt.input-group-addon
            = label_tag "帐号"
          %dd
            = text_field_tag :name, params[:name], :class => "form-control",:placeholder => "请输入帐号"
        %dl.input-group
          %dt.input-group-addon
            = label_tag "密码"
          %dd
            = password_field_tag :password, params[:password], :class => "form-control",:placeholder => "请输入密码"
        = link_to "忘记密码",forgot_password_1_path, :class => "right"
        - if flash[:error]
          .alert.alert-danger
            = flash[:error]
        %p
          = submit_tag "登录", :class => "btn-default btn btm-primary"

app/views/users/password.erb
<div class="modal" id = "alert">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"></h4>
      </div>
      <div class="modal-body text-center">
        <h4>修改成功</h4>
      </div>
      <div class="modal-footer">
        <%= link_to "确定", welcome_path, :class => "btn btn-default"%>
      </div>
    </div>
  </div>
</div>
<ol class="breadcrumb">
  <li><%= link_to_unless_current "首页", welcome_path %></li>
  <li><%= link_to_unless_current "修改密码", password_path %></li>
</ol>
<div class="panel panel-default panel-body text-center center-block width" style="background-color: #eeeeee">
  <%= form_tag "change_password_session" do %>
      <div class="center-block">
        <div class="">
          <dl class="input-group">
            <dt class="input-group-addon input_width-1">&nbsp&nbsp帐&nbsp&nbsp&nbsp号&nbsp&nbsp</dt>
            <dd class=""><%= text_field_tag :name, session[:name], :disabled => 'disabled', :class => "form-control" %></dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon input_width-1">设置密码</dt>
            <dd class=""> <%= text_field_tag :password, params[:password], :class => "form-control" %> </dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon input_width-1">确认密码</dt>
            <dd class=""> <%= text_field_tag :password_confirmation, params[:password_confirmation], :class => "form-control" %></dd>
          </dl>
          <% if flash[:error] %>
              <div class="alert alert-danger">
                <%= flash[:error] %>
              </div>
          <% end %>
          <% if flash[:notice] == "ok" %>
              <% flash[:notice] = "" %>
              <script language="javascript">
                  $('#alert').modal('show')
              </script>
          <% end %>
          <p><%= submit_tag "确认修改", :class => "btn-default btn btm-primary" %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/users/pricelist.haml
= render 'shared/header'
%ol.breadcrumb
  .winner(align = 'center')
    - status = BidList.where(:username => params[:username],:activityname => params[:activityname],:bidname => params[:bidname])
    - pricecount = PriceCount.where(:username => params[:username],:activityname => params[:activityname],:bidname => params[:bidname])
    -if status.find_by_status("1") && pricecount.find_by_count("1")
      - success = pricecount.where(:count => 1).first
      - people = BidMessage.where(:username =>  params[:username],:activityname => params[:activityname],:bidname => params[:bidname],:price => success.price).first
      %p
        = "获胜者:" + people.name
      %p
        = "出价:" + people.price + "元"
      %p
        = "手机号:" + people.phone
    -else
      -if status.find_by_status("0")
        活动正在进行中...
      -else
        本次竞价无人胜出
.panel.panel-default{:style => "width: 95%;margin-left: 35px"}
  %table.table.text-center
    %thead
      %ul.nav.nav-tabs.nav-justified
        %li.active
          %a
            出价列表
        %li
          =link_to "价格统计",pricecount_path(:username =>  params[:username],:activityname => params[:activityname],:bidname => params[:bidname])
    %tr
      %td{:style => "width: 22%"} 编号
      %td{:style => "width: 22%"} 姓名
      %td{:style => "width: 22%"} 价格/元
      %td{:style => "width: 34%"} 手机号
      - bidmessage = BidMessage.where(:username =>  params[:username],:activityname => params[:activityname],:bidname => params[:bidname])
      - @bidmessage = bidmessage.paginate(page: params[:page],per_page:10)
    - if params[:page].to_i == 0
      - id = 0
    - else
      - id = (params[:page].to_i-1)*10
    - @bidmessage.each do |p|
      %tr
        %td{:style => "width: 22%"}= id =id+1
        %td{:style => "width: 22%"}= p.name
        %td{:style => "width: 22%"}= p.price+"元"
        %td{:style => "width: 34%"}= p.phone
.pagination{:style => "position: absolute;right: 30px; "}
  = will_paginate @bidmessage, {:previous_label => '<<', :next_label => '>>'}

app/views/users/show.haml
- if Message.first.status == "1"
  #show
    %ol.breadcrumb
      .winner(align = 'center')
        %p{:style => "font-size: 50px"}
          - message = Message.first.name
          = message
        %p{:style => "font-size: 25px"}
          = "参与人数："
          - a = 0
          - @bid_count.each do |b|
            - a = a + b.count.to_i
          = a
          = "/"
          = Activity.where(:username =>  current_user.name,:activityname => message).count
    .panel.panel-default{:style => "width: 95%;margin-left: 35px"}
      %table.table.text-center
        %tr
          %td{:style => "width: 50%"} 姓名
          %td{:style => "width: 50%"} 电话
        - @bid.each do |p|
          %tr
            %td{:style => "width: 50%"}= p.name
            %td{:style => "width: 50%"}= p.phone
  %script{:language => "javascript"}
    setTimeout(function(){location.reload('#show')},3000)
- else
  - bid = Bid.where(:count => 1).first
  - if bid
    %ol.breadcrumb
      .winner(align = 'center')
        %p{:style => "font-size: 75px"}
          - message = Message.first.name
          = message
        %p{:style => "font-size: 45px"}
          = "比赛结果:"
        %P{:style => "font-size: 30px"}
          = "获胜者："
          = bid.name
        %P{:style => "font-size: 30px"}
          = "出价："
          = bid.price
        %P{:style => "font-size: 30px"}
          = "电话："
          = bid.phone
  - else
    %ol.breadcrumb
      .winner(align = 'center')
        %p{:style => "font-size: 75px"}
          - message = Message.first.name
          = message
        %p{:style => "font-size: 45px"}
          = "比赛结果:无胜出者"

app/views/users/signup.erb
<div class="panel panel-default panel-body text-center center-block width" style = "background-color: #eeeeee">
  <%= form_for @user do |f| %>
      <div class="center-block">
        <h3 class="">新用户注册</h3>
        <%= link_to "用户登录", login_path, :class => "right" %>
        <div class="">
          <dl class="input-group">
            <dt class="input-group-addon"><%= f.label :name, :class => "input_width-1" %></dt>
            <dd class=""><%= f.text_field :name, :class => "form-control" %></dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon"> <%= f.label :password, :class => "input_width-1" %> </dt>
            <dd class=""> <%= f.password_field :password, :class => "form-control" %> </dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon"> <%= f.label :password_confirmation, :class => "input_width-1" %> </dt>
            <dd class=""> <%= f.password_field :password_confirmation, :class => "form-control" %></dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon"> <%= f.label :forget_issues %> </dt>
            <dd class=""> <%= f.text_field :forget_issues, :class => "form-control" %> </dd>
          </dl>
          <dl class="input-group">
            <dt class="input-group-addon"> <%= f.label :forget_answer %> </dt>
            <dd class=""> <%= f.text_field :forget_answer, :class => "form-control" %> </dd>
          </dl>
          <% if @user.errors.any? %>
              <div class = "alert alert-danger">
                <%= @user.errors.full_messages.first %>
              </div>
          <% end %>
          <p><%= f.submit "注册", :class => "btn-default btn btm-primary" %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/users/signuplist.haml
= render 'shared/header'
.panel.panel-default{:style => "width: 95%;margin-left: 35px"}
  .panel-heading
    %p{:style => "font-size: 25px"}
      报名列表
    %p{:style => "font-size: 15px;position: absolute;right: 50px;top: 110px"}
      = link_to "竞价列表",bidlist_path(:username =>  params[:username],:activityname => params[:activityname])
    - signupmessage = Activity.where(:username => params[:username],:activityname => params[:activityname])
    - @signupmessage = signupmessage.paginate(page: params[:page],per_page:10)
  %table.table.text-center
    %tr
      %td{:style => "width: 30%"} 编号
      %td{:style => "width: 30%"} 姓名
      %td{:style => "width: 40%"} 手机号
    - if params[:page].to_i == 0
      - id = 0
    - else
      - id = (params[:page].to_i-1)*10
    - @signupmessage.each do |p|
      %tr
        %td{:style => "width: 30%"}= id =id+1
        %td{:style => "width: 30%"}= p.name
        %td{:style => "width: 40%"}= p.phone
.pagination{:style => "position: absolute;right: 30px; "}
  = will_paginate @signupmessage, {:previous_label => '<<', :next_label => '>>'}

app/views/users/welcome.erb
<% if current_user %>
    <% if current_user.identity == "admin" %>
        <div class="panel panel-default" style="width: 95%;margin-left: 35px">
          <div class="panel-heading" style="font-size: 25px">
            用户管理
            <button class="btn btn-default"><%= link_to "+添加用户", adduser_path %></button>
          </div>
          <table class="table text-center">
            <tr>
              <td style="width: 350px">编号</td>
              <td style="width: 350px">用户名</td>
              <td>操作</td>
            </tr>
            <%= @a %>
            <% if params[:page].to_i == 0 %>
                <% id = 0 %>
            <% else %>
                <% id = (params[:page].to_i-1)*10 %>
            <% end %>
            <% @user.each do |p| %>
                <tr>
                  <td style="width: 350px"><%= id =id+1 %></td>
                  <td style="width: 350px"><%= p.name %></td>
                  <td>
                    <%= link_to "删除", delete_user_path(:delete_name => p[:name]), data: {confirm: "确定要删除"+p[:name]+"这个用户？"}, method: "delete" %>
                    &nbsp&nbsp&nbsp&nbsp<%= link_to "修改密码", password_path(:change_name => p[:name]) %>
                  </td>
                </tr>
            <% end %>
          </table>
        </div>
        <div class="pagination" style="position: absolute;right: 30px; ">
          <%= will_paginate @user, {:previous_label => '<<', :next_label => '>>'} %>
        </div>
    <% end %>
<% end %>

app/views/users/welcome.haml
= render 'shared/header'
.panel.panel-default{:style => "width: 95%;margin-left: 35px"}
  .panel-heading{:style => "font-size: 25px"}
    活动信息
    = link_to "同步展示",synchronous_show_path,:class => "btn btn-default",:style => "position: absolute;right: 50px;",method: "post"
  %table.table.text-center
    %tr
      %td{:style => "width: 25%"} 编号
      %td{:style => "width: 25%"} 活动名称
      %td{:style => "width: 25%"} 报名人数
      %td{:style => "width: 25%"} 竞价次数
    - if params[:page].to_i == 0
      - id = 0
    - else
      - id = (params[:page].to_i-1)*10
    - @activity.each do |p|
      %tr
        %td{:style => "width: 25%"}= id =id+1
        %td{:style => "width: 25%"}= link_to p.activityname,bidlist_path(:username => p[:username],:activityname => p[:activityname])
        %td{:style => "width: 25%"}= link_to Activity.where(:username => p.username,:activityname => p.activityname).count,signuplist_path(:username => p[:username],:activityname => p[:activityname])
        %td{:style => "width: 25%"}= BidList.where(:username => p.username,:activityname => p.activityname).count
.pagination{:style => "position: absolute;right: 30px; "}
  = will_paginate @activity, {:previous_label => '<<', :next_label => '>>'}