config/routes.rb
Rails.application.routes.draw do
  root to: "users#login", :as => "login"

  get "/signup" => "users#signup", :as => "signup"

  get "/welcome" => "users#welcome", :as => "welcome"

  get "/admin_welcome" => "admins#admin_welcome", :as => "admin_welcome"

  get "/adduser" => "users#adduser", :as => "adduser"

  get "/password" => "admins#password", :as => "password"

  get "/forgot_password_1" => "users#forgot_password_1"

  get "/forgot_password_2" => "users#forgot_password_2"

  get "/forgot_password_3" => "users#forgot_password_3"

  get "/signuplist" => "users#signuplist"

  get "/bidlist" => "users#bidlist"

  get "/pricelist" => "users#pricelist"

  get "/pricecount" => "users#pricecount"

  get "user_two" => "admins#user_two"

  get "show" => "users#show"

  post "user_two" => "admins#user_two"

  post "forgot_password_one" => "users#forgot_password_one"

  post "forgot_password_two" => "users#forgot_password_two"

  post "forgot_password_three" => "users#forgot_password_three"

  post "create_login_session" => "users#create_login_session"

  post "change_password_session" => "admins#change_password_session"

  post "login_activity"  => "users#login_activity"

  post "synchronization" =>  "users#synchronization"

  post "synchronous_bid" => "users#synchronous_bid"

  post "start" => "users#start"

  post "end" => "users#end"

  post "synchronous_show" => "users#synchronous_show"

  post "synchronization_two" => "users#synchronization_two"

  delete "delete_user" => "users#delete_user", :as => "delete_user"

  delete "logout" => "users#logout", :as => "logout"

  delete "logout_two" => "users#logout_two"

  resources :users, only: [:create]

end

app/views/shared/_header.erb
<header class="navbar navbar-default container-fluid">
  <h1>活动通</h1>
  <% if current_user %>
      <li class = "header-right">你好，<%= link_to_unless_current current_user.name,welcome_path %>！  <%= link_to "退出", logout_path, method: "delete" %></li>
  <% end %>
</header>

app/views/shared/_header.haml
%header.navbar.navbar-default.container-fluid
  %h1 活动通
  - if current_user
    %li.header-right
      - if current_user.identity == "admin"
        - if current_user_two
          你好，#{link_to_unless_current current_user_two.name,welcome_path}！  #{link_to "退出", logout_two_path, method: "delete"}
        你好，#{link_to_unless_current current_user.name,admin_welcome_path}！  #{link_to "退出", logout_path, method: "delete"}
      - else
        你好，#{link_to_unless_current current_user.name,welcome_path}！  #{link_to "退出", logout_path, method: "delete"}